my_dict = {
'fa':'der Baum, die Bäume',
'autó':'das Auto, die Autos',
'macska':'die Katze, die Katzen',
'ablak':'das Fenster, die Fenster',
'agy':'das Gehirn, die Gehirne',
'ágy':'das Bett, die Betten',
'anya':'die Mutter, die Mütter',
'arc':'das Gesicht, die Gesichter',
'áruház':'das Warenhaus, die Warenhäuser',
'barát':'der Freund, die Freunde',
'barátnő':'die Freundin, die Freundinnen',
'kérelem':'der Antrag, die Anträge',
'a beteg':'der Krank, die Kranke',
'busz':'der Bus, die Busse',
'ceruza':'der Bleistiff, die Bleistiffe',
'csúcs, hegycsúcs':'die Spitze, die Spitzen',
'vonat':'der Zug, die Züge',
'villamos':'die Straßenbahn, die Straßenbahnen',
'vihar':'der Sturm, die Stürme',
'verseny':'der Wettbewerb, die Wettbewerbe',
'vendég':'der Gast, die Gäste',
'vélemény':'die Meinung, die Meinungen',
'véleményem szerint':'nach meiner Meinung',
'vég, vége':'das Ende, die Enden',
'dzseki':'die Jacke, die Jacken',
'diák(fiú)':'der Schüler, die Schüler',
'diák(lány)':'die Schülerin, die Schülerinnen',
'befolyásol':'beeinflussen, beinflusste, hat beeinflusst',
'bérel':'mieten, mietete, hat gemietet',
'birtokol':'haben, hatte, hat gehabt',
'bizonyára':'bestimmt',
'borotválkozik':'rasieren sich, rasierte sich, hat rasiert sich',
'büszkének lenni vkire':'stolz auf + D sein',
'cipőt pucol':'Schuhe putzen',
'csinos':'hübsch',
'drága':'teuer',
'együtt':'miteinander',
'együtt lakik':'zusammenleben, lebte zusammen, hat zusammengelebt',
'éjszakázik':'übernachten, übernachtete, hat übernachtet',
'elér':'erreichen, erreichte, hat erreicht',
'elhalaszt':'verzögern, verzögerte, hat verzögert',
'elkap':'schnappen, schnappte, hat geschnappt',
'elkésik':'verspäten sich, verspätete, hat verspätet',
'elkísér':'begleiten, begleitete, hat begleitet',
'elköltözik':'ausziehen, zog aus, ist ausgezogen',
'élmény, tapasztalat':'das Erlebnis, die Erlebnisse',
'eltölt':'verbringen, verbrachte, hat verbracht',
'elutazik':'abfahren, fuhr ab, ist abgefahren',
'elvégez, befejez':'absolvieren, absolvierte, hat absolviert',
'érdekel vkit vmi':'interessieren sich, interessierte, hat interessiert',
'érzi magát vhogy':'füllen sich, füllte, hat gefüllt',
'esküvő':'die Hochzeit, die Hochzeiten',
'eszik':'essen, aß, hat gegessen',
'étel':'die Speise, die Speisen',
'étkezés':'das Essen, die Essen',
'fal':'die Wand, die Wände',
'fáradt':'müde',
'tudás':'die Kenntniss, die Kenntnisse',
'tömegközlekedés':'der Massenverkehr, die Massenverkehre',
'tol':'drücken, drückte, hat gedrückt',
'fejlődik':'entwickeln sich, entwickelte, hat entwickelt',
'felcipel':'hinauf schleppen, schleppte, hat geschleppt',
'felhív':'anrufen, rief an, hat angerufen',
'felkel':'aufstehen, stand auf, ist aufgestanden',
'felöltözik':'aufnehmen, nahm auf, hat aufgenommen',
'felszáll':'einsteigen + A, stieg ein, ist eingestiegen',
'fésű':'der Kamm, die Kämme',
'fog, fogak':'der Zahn, die Zähne',
'fogat mos':'die Zähne putzen, putzte, hat geputzt',
'foglalkozás':'der Beruf, die Berufe',
'foglalkozik vmivel':'beschäftigen sich mit + D, beschäftigte, hat beschäftigt',
'folyamatos':'fortläufend',
'folyékonyan':'fließend',
'folyik':'fließen, floss, ist geflossen',
'folyó':'der Fluss, die Flüsse',
'függ, lóg, akaszt':'hängen, hing, hat gehangen',
'függőség':'die Abhängigkeit, die Abhängigkeiten',
'fürdő':'das Bad, die Bäder',
'fut':'laufen, lief, ist gelaufen',
'generáció':'die Generation, die Generationen',
'golyóstoll':'der Kugelschreiber, die Kugelschreiber',
'gondolat':'der Gedanke, die Gedanken',
'gyalogol':'zu Fuss gehen, ging, ist gegangen',
'gyümölcs':'das Obst, -',
'hasonló':'ähnlich + D',
'hátizsák':'der Rucksack, die Rucksäcke',
'házi feladat':'die Hausaufgabe, die Hausaufgaben',
'hegység':'das Gebirge, die Gebirge',
'hely, helység':'der Ort, die Orte',
'hétvége':'das Wochenende, die Wochenenden',
'hibásnak lenni vmiben':'schuld sein an + D, war, ist gewesen',
'híres':'berühmt',
'húz':'ziehen, zog, ist gezogen',
'ideges':'nervös',
'idő':'die Zeit, die Zeiten',
}